In [1]:
import numpy as np 
import plotly.express as px 
import pandas as pd
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import skimpy

In [7]:
aliens = pd.read_csv("./data/aliens.csv")
details = pd.read_csv("./data/details.csv")
location = pd.read_csv("./data/location.csv")

In [8]:
aliens.head()

,id,first_name,last_name,email,gender,type,birth_year
0,1,Tyrus,Wrey,twrey0@sakura.ne.jp,Agender,Reptile,1717
1,2,Ealasaid,St Louis,estlouis1@amazon.co.uk,Female,Flatwoods,1673
2,3,Violette,Sawood,vsawood2@yolasite.com,Female,Nordic,1675
3,4,Rowan,Saintsbury,rsaintsbury3@rediff.com,Male,Green,1731
4,5,Free,Ingolotti,fingolotti4@bbb.org,Genderfluid,Flatwoods,1763

In [9]:
details.head()

   detail_id              favorite_food feeding_frequency  aggressive
0          1       White-faced tree rat            Weekly        True
1          2             Lizard, goanna            Seldom       False
2          3         Indian red admiral            Weekly        True
3          4  Bandicoot, southern brown             Often       False
4          5              Kangaroo, red              Once       False

In [10]:
location.head()

   loc_id current_location       state        country              occupation
0       1       Cincinnati        Ohio  United States  Senior Cost Accountant
1       2         Bethesda    Maryland  United States  Senior Sales Associate
2       3          Oakland  California  United States        Registered Nurse
3       4         Richmond    Virginia  United States       Director of Sales
4       5          Atlanta     Georgia  United States  Administrative Officer

In [15]:
print(skimpy.skim(aliens))

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 50000  │ │ string      │ 5     │                                                          │
│ │ Number of columns │ 7      │ │ int64       │ 2     │                                                          │
│ └───────────────────┴────────┘ └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃ column_name      ┃ NA   ┃ NA %    ┃ mean     ┃ sd       ┃ p0     ┃ p25      ┃ p75     ┃ p100    ┃ hist     ┃  │
│ ┡━━━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━┩  │
│ │ id               │    0 │       0 │    25000 │    14000 │      1 │    13000 │   38000 │   50000 │  ██████  │  │
│ │ birth_year       │    0 │       0 │     1800 │       87 │   1700 │     1700 │    1900 │    2000 │  ██████  │  │
│ └──────────────────┴──────┴─────────┴──────────┴──────────┴────────┴──────────┴─────────┴─────────┴──────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column_name               ┃ NA      ┃ NA %       ┃ words per row                ┃ total words              ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━┩  │
│ │ first_name                │       0 │          0 │                            1 │                    50000 │  │
│ │ last_name                 │       0 │          0 │                            1 │                    50000 │  │
│ │ email                     │       0 │          0 │                            1 │                    50000 │  │
│ │ gender                    │       0 │          0 │                            1 │                    50000 │  │
│ │ type                      │       0 │          0 │                            1 │                    50000 │  │
│ └───────────────────────────┴─────────┴────────────┴──────────────────────────────┴──────────────────────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

None

In [13]:
skimpy.skim(details)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 50000  │ │ string      │ 2     │                                                          │
│ │ Number of columns │ 4      │ │ int64       │ 1     │                                                          │
│ └───────────────────┴────────┘ │ bool        │ 1     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃ column_name       ┃ NA   ┃ NA %    ┃ mean     ┃ sd       ┃ p0   ┃ p25      ┃ p75      ┃ p100    ┃ hist     ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━┩  │
│ │ detail_id         │    0 │       0 │    25000 │    14000 │    1 │    13000 │    38000 │   50000 │  ██████  │  │
│ └───────────────────┴──────┴─────────┴──────────┴──────────┴──────┴──────────┴──────────┴─────────┴──────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column_name                       ┃ NA     ┃ NA %      ┃ words per row             ┃ total words           ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━┩  │
│ │ favorite_food                     │      0 │         0 │                       2.2 │                110000 │  │
│ │ feeding_frequency                 │      0 │         0 │                       2.2 │                110000 │  │
│ └───────────────────────────────────┴────────┴───────────┴───────────────────────────┴───────────────────────┘  │
│                                                      bool                                                       │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column_name                       ┃ true              ┃ true rate                    ┃ hist                ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩  │
│ │ aggressive                        │             25000 │                          0.5 │       █    █        │  │
│ └───────────────────────────────────┴───────────────────┴──────────────────────────────┴─────────────────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

In [14]:
skimpy.skim(location)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 50000  │ │ string      │ 4     │                                                          │
│ │ Number of columns │ 5      │ │ int64       │ 1     │                                                          │
│ └───────────────────┴────────┘ └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃ column_name       ┃ NA   ┃ NA %    ┃ mean     ┃ sd       ┃ p0   ┃ p25      ┃ p75      ┃ p100    ┃ hist     ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━┩  │
│ │ loc_id            │    0 │       0 │    25000 │    14000 │    1 │    13000 │    38000 │   50000 │  ██████  │  │
│ └───────────────────┴──────┴─────────┴──────────┴──────────┴──────┴──────────┴──────────┴─────────┴──────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column_name                      ┃ NA     ┃ NA %      ┃ words per row              ┃ total words           ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━┩  │
│ │ current_location                 │      0 │         0 │                        1.3 │                 65000 │  │
│ │ state                            │      0 │         0 │                        1.3 │                 65000 │  │
│ │ country                          │      0 │         0 │                        1.3 │                 65000 │  │
│ │ occupation                       │      0 │         0 │                        1.3 │                 65000 │  │
│ └──────────────────────────────────┴────────┴───────────┴────────────────────────────┴───────────────────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

In [19]:
# grouping all the 3 above dataframes into the one 
combined_df = pd.merge(aliens, details, left_on='id', right_on = "detail_id")
combined_df = pd.merge(combined_df, location, left_on='id', right_on = "loc_id")
combined_df.head()

# removing loc_id , detail_id and id columsn 
combined_df.drop(['loc_id', 'detail_id',  "id"], axis=1, inplace=True)

In [20]:
skimpy.skim(combined_df)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 50000  │ │ string      │ 11    │                                                          │
│ │ Number of columns │ 13     │ │ int64       │ 1     │                                                          │
│ └───────────────────┴────────┘ │ bool        │ 1     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━┓  │
│ ┃ column_name        ┃ NA    ┃ NA %    ┃ mean    ┃ sd   ┃ p0      ┃ p25     ┃ p75     ┃ p100    ┃ hist       ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━┩  │
│ │ birth_year         │     0 │       0 │    1800 │   87 │    1700 │    1700 │    1900 │    2000 │   ██████   │  │
│ └────────────────────┴───────┴─────────┴─────────┴──────┴─────────┴─────────┴─────────┴─────────┴────────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column_name                       ┃ NA     ┃ NA %      ┃ words per row             ┃ total words           ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━┩  │
│ │ first_name                        │      0 │         0 │                         1 │                 50000 │  │
│ │ last_name                         │      0 │         0 │                         1 │                 50000 │  │
│ │ email                             │      0 │         0 │                         1 │                 50000 │  │
│ │ gender                            │      0 │         0 │                         1 │                 50000 │  │
│ │ type                              │      0 │         0 │                         1 │                 50000 │  │
│ │ favorite_food                     │      0 │         0 │                         1 │                 50000 │  │
│ │ feeding_frequency                 │      0 │         0 │                         1 │                 50000 │  │
│ │ current_location                  │      0 │         0 │                         1 │                 50000 │  │
│ │ state                             │      0 │         0 │                         1 │                 50000 │  │
│ │ country                           │      0 │         0 │                         1 │                 50000 │  │
│ │ occupation                        │      0 │         0 │                         1 │                 50000 │  │
│ └───────────────────────────────────┴────────┴───────────┴───────────────────────────┴───────────────────────┘  │
│                                                      bool                                                       │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column_name                       ┃ true              ┃ true rate                    ┃ hist                ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩  │
│ │ aggressive                        │             25000 │                          0.5 │       █    █        │  │
│ └───────────────────────────────────┴───────────────────┴──────────────────────────────┴─────────────────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

In [23]:
combined_df.head()

,first_name,last_name,email,gender,type,birth_year,favorite_food,feeding_frequency,aggressive,current_location,state,country,occupation
0,Tyrus,Wrey,twrey0@sakura.ne.jp,Agender,Reptile,1717,White-faced tree rat,Weekly,True,Cincinnati,Ohio,United States,Senior Cost Accountant
1,Ealasaid,St Louis,estlouis1@amazon.co.uk,Female,Flatwoods,1673,"Lizard, goanna",Seldom,False,Bethesda,Maryland,United States,Senior Sales Associate
2,Violette,Sawood,vsawood2@yolasite.com,Female,Nordic,1675,Indian red admiral,Weekly,True,Oakland,California,United States,Registered Nurse
3,Rowan,Saintsbury,rsaintsbury3@rediff.com,Male,Green,1731,"Bandicoot, southern brown",Often,False,Richmond,Virginia,United States,Director of Sales
4,Free,Ingolotti,fingolotti4@bbb.org,Genderfluid,Flatwoods,1763,"Kangaroo, red",Once,False,Atlanta,Georgia,United States,Administrative Officer

In [25]:
combined_df.state.value_counts()

Texas                   5413
California              5410
Florida                 4176
New York                2690
Ohio                    1851
Virginia                1749
District of Columbia    1661
Pennsylvania            1590
Georgia                 1431
North Carolina          1248
Illinois                1223
Colorado                1175
Arizona                 1122
Missouri                1102
Minnesota               1067
Alabama                 1066
Indiana                 1056
Michigan                1016
Washington               971
Louisiana                951
Tennessee                934
Massachusetts            767
Oklahoma                 756
Kentucky                 699
Connecticut              697
Kansas                   676
Nevada                   660
Maryland                 598
Wisconsin                579
South Carolina           554
Iowa                     537
West Virginia            484
New Jersey               474
Utah                     435
Nebraska                 420
Oregon                   413
New Mexico               309
Arkansas                 282
Mississippi              282
Hawaii                   227
Idaho                    220
Alaska                   204
Delaware                 192
Montana                  144
South Dakota             141
North Dakota             109
New Hampshire             92
Rhode Island              53
Maine                     32
Wyoming                   32
Vermont                   30
Name: state, dtype: Int64

In [36]:
x =pd.DataFrame(columns = ["state" ,"count" ])
x["state"] = combined_df['state'].value_counts().to_dict().keys()
x["count"] = combined_df['state'].value_counts().to_dict().values()
x

                   state  count
0                  Texas   5413
1             California   5410
2                Florida   4176
3               New York   2690
4                   Ohio   1851
5               Virginia   1749
6   District of Columbia   1661
7           Pennsylvania   1590
8                Georgia   1431
9         North Carolina   1248
10              Illinois   1223
11              Colorado   1175
12               Arizona   1122
13              Missouri   1102
14             Minnesota   1067
15               Alabama   1066
16               Indiana   1056
17              Michigan   1016
18            Washington    971
19             Louisiana    951
20             Tennessee    934
21         Massachusetts    767
22              Oklahoma    756
23              Kentucky    699
24           Connecticut    697
25                Kansas    676
26                Nevada    660
27              Maryland    598
28             Wisconsin    579
29        South Carolina    554
30                  Iowa    537
31         West Virginia    484
32            New Jersey    474
33                  Utah    435
34              Nebraska    420
35                Oregon    413
36            New Mexico    309
37              Arkansas    282
38           Mississippi    282
39                Hawaii    227
40                 Idaho    220
41                Alaska    204
42              Delaware    192
43               Montana    144
44          South Dakota    141
45          North Dakota    109
46         New Hampshire     92
47          Rhode Island     53
48                 Maine     32
49               Wyoming     32
50               Vermont     30

Texas                   5413
California              5410
Florida                 4176
New York                2690
Ohio                    1851
Virginia                1749
District of Columbia    1661
Pennsylvania            1590
Georgia                 1431
North Carolina          1248
Illinois                1223
Colorado                1175
Arizona                 1122
Missouri                1102
Minnesota               1067
Alabama                 1066
Indiana                 1056
Michigan                1016
Washington               971
Louisiana                951
Tennessee                934
Massachusetts            767
Oklahoma                 756
Kentucky                 699
Connecticut              697
Kansas                   676
Nevada                   660
Maryland                 598
Wisconsin                579
South Carolina           554
Iowa                     537
West Virginia            484
New Jersey               474
Utah                     435
Nebraska                 420
Oregon                   413
New Mexico               309
Arkansas                 282
Mississippi              282
Hawaii                   227
Idaho                    220
Alaska                   204
Delaware                 192
Montana                  144
South Dakota             141
North Dakota             109
New Hampshire             92
Rhode Island              53
Maine                     32
Wyoming                   32
Vermont                   30
Name: state, dtype: Int64